#!/bin/bash
# Beep while the internet is down

getopts l LOUD
while true
do
  ping -c 1 -w 3 google.com
  RETVAL=$?
  [ $RETVAL -ne 0 ] && notify-send "Internet Down!"  && [ $LOUD ] && cvlc ./beep-01a.mp3 &
  sleep 5
done
